spring:
  application:
    name : "TelegramBot"
  datasource:
    driver_class_name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:4321/TraderDB
    username: postgres
    password: postgres

app:
  telegram-token: 7424392616:AAEKAIDNyybDZ_DE8PcNxAWN8NJggvaDgXA
server:
  port: 8888