spring:
  application:
    name : "DataProcessor"
  datasource:
    driver_class_name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:4321/TraderDB
    username: postgres
    password: postgres
  liquibase:
    enabled: false
server:
  port: 8090
app:
  aggregateScheduler:
    enable: true
    interval: 1m
  sendScheduler:
    enable: true
    interval: 5m