spring:
  application:
    name: "ClientService"
  datasource:
    driver_class_name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:4321/TraderDB
    username: postgres
    password: postgres
  liquibase:
    enabled: false
server:
  port: 9888
jwt:
  secret: "ocheni_nadezniy_kluch_otvechau_xren_vzlomaesh"
  lifetime: 900000

