spring:
  application:
    name : "DataLoader"
  datasource:
    driver_class_name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:4321/TraderDB
    username: postgres
    password: postgres
  liquibase:
    enabled: false
server:
  port: 8080
app:
  token: "t.rNoz7VuY6Obq4WttMikAopqywLLeVzQOzOh4YI0EXdHYyHPcdaT5Aug24DGHmXUpUVrzafRZuyhL6Ks-Cqs6DA"
  scheduler:
    enable: true
    interval: 20s

